/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:bstart:927606:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());  
} //_CODE_:bstart:927606:

public void button2_click1(GButton source, GEvent event) { //_CODE_:bquit:562988:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:bquit:562988:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.YELLOW_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  bstart = new GButton(this, 352, 368, 336, 96);
  bstart.setText("Start");
  bstart.setTextBold();
  bstart.setLocalColorScheme(GCScheme.RED_SCHEME);
  bstart.addEventHandler(this, "button1_click1");
  bquit = new GButton(this, 352, 512, 336, 96);
  bquit.setText("Quit");
  bquit.setTextBold();
  bquit.setLocalColorScheme(GCScheme.RED_SCHEME);
  bquit.addEventHandler(this, "button2_click1");
  l1 = new GLabel(this, 240, 16, 560, 304);
  l1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  l1.setText("PLAY SPACEPULSE");
  l1.setTextBold();
  l1.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  l1.setOpaque(true);
}

// Variable declarations 
// autogenerated do not edit
GButton bstart; 
GButton bquit; 
GLabel l1; 
